import { BgGradient } from "./components/bg-gradient";
import "./globals.css";

export const metadata = {
  title: "User Management",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black">
        <BgGradient className="absolute w-screen h-auto flex -z-10" />
        <div>{children}</div>
      </body>
    </html>
  );
}
